// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection

export enum Events {
  copy = "copy",
  paste = "paste",
  cut = "cut",
  keydown = "keydown",
  keyup = "keyup",
  mouseMove = "mousemove",
  resize = "resize",
  unload = "unload",
  focus = "focus",
  blur = "blur",
  dragOver = "dragover",
  drop = "drop",
  gestureEnd = "gestureend",
  beforeUnload = "beforeunload",
  gestureStart = "gesturestart",
  gestureChange = "gesturechange",
  pointerMove = "pointermove",
  pointerUp = "pointerup",
  stateChange = "statechange",
  wheel = "wheel",
  touchStart = "touchstart",
  touchEnd = "touchend",
  hashchange = "hashchange",
  visibilityChange = "visibilitychange",
  scroll = "scroll",
}